[workspace]
channels = ["conda-forge"]
name = "dotfiles"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
basedpyright = ">=1.37.4,<2"
ruff = ">=0.15.0,<0.16"
ty = ">=0.0.17,<0.0.18"
