# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j10 -l11"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
L10N="en en-US zh zh-CN zh-TW"
LINGUAS="en en_US zh zh_CN zh_TW"

USE="symlink systemd udev dbus policykit networkmanager bluetooth git wayland X pipewire pulseaudio alsa vappi grub wayland vulkan abi_x86_32 dist-kernel"

GENTOO_MIRRORS="https://mirrors.ustc.edu.cn/gentoo/"

ACCEPT_LICENSE="*"

EMERGE_DEFAULT_OPTS="--ask --verbose --jobs=3 --load-average=11"

FEATURES="parallel-fetch parallel-install candy ccache"

GRUB_PLATFORMS="efi-64"

# 记录哪些级别的日志
PORTAGE_ELOG_CLASSES="warn error log qa"

# 日志保存方式
PORTAGE_ELOG_SYSTEM="save"  # 保存到 /var/log/portage/elog/

KERNEL_CC="clang"
KERNEL_LD="ld.lld"
