[config]
# ...

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.fish]
input_path = '~/.config/matugen/templates/fish.stpl'
output_path = '~/.config/fish/conf.d/colors.fish'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.television]
input_path = '~/.config/matugen/templates/television.toml'
output_path = '~/.config/television/themes/matugen.toml'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors/matugen.kdl'

[templates.firefox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
