--=============================================================================
-- Theme
--=============================================================================
-- Load Stylix base16 colors (generated by home-manager, see nix/homeModules/stylix.nix)
local c = dofile(vim.fn.expand("~/.config/stylix-nvim/base16.lua"))


--=============================================================================
-- mini.base16 — base16 color scheme using Stylix palette
--=============================================================================
require("mini.base16").setup({ palette = c })

-- Transparent backgrounds
local set_hl = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

set_hl("Normal",       { bg = "NONE" })
set_hl("NonText",      { bg = "NONE" })
set_hl("LineNr",       { bg = "NONE" })
set_hl("LineNrAbove",  { bg = "NONE" })
set_hl("LineNrBelow",  { bg = "NONE" })
set_hl("SignColumn",   { bg = "NONE" })
set_hl("NormalFloat",  { bg = "NONE" })
set_hl("FloatBorder",  { bg = "NONE" })

-- Re-apply transparency if colorscheme is reloaded
vim.api.nvim_create_autocmd("ColorScheme", {
  group = vim.api.nvim_create_augroup("stylix_transparent", { clear = true }),
  pattern = "*",
  callback = function()
    set_hl("Normal",      { bg = "NONE" })
    set_hl("NonText",     { bg = "NONE" })
    set_hl("LineNr",      { bg = "NONE" })
    set_hl("LineNrAbove", { bg = "NONE" })
    set_hl("LineNrBelow", { bg = "NONE" })
    set_hl("SignColumn",  { bg = "NONE" })
    set_hl("NormalFloat", { bg = "NONE" })
    set_hl("FloatBorder", { bg = "NONE" })
  end,
})

require('mini.notify').setup()
require('mini.statusline').setup()
require('mini.tabline').setup()
