---@diagnostic disable: unused-local, redundant-parameter
local gh = function(x) return "https://github.com/" .. x end

--=============================================================================
-- Theme
--=============================================================================
vim.pack.add({
  gh("nvim-mini/mini.icons"),
  gh("nvim-mini/mini.base16"),
  gh("mvllow/modes.nvim"),
})

-- Load Stylix base16 colors (generated by home-manager, see nix/homeModules/stylix.nix)
local c = dofile(vim.fn.expand("~/.config/stylix-nvim/base16.lua"))

-- mini.icons — lightweight, needed by UI components (tabline, lualine, telescope)
require("mini.icons").setup()

-- modes.nvim – cursor color by mode
require("modes").setup({
  colors = {
    bg = "",
    copy = c.base0A,
    delete = c.base08,
    change = c.base0B,
    format = c.base09,
    insert = c.base0C,
    replace = c.base0D,
    select = c.base0E,
    visual = c.base0E,
  },
})

--=============================================================================
-- mini.base16 — base16 color scheme using Stylix palette
--=============================================================================
require("mini.base16").setup({ palette = c })

-- Transparent backgrounds
local set_hl = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

set_hl("Normal",       { bg = "NONE" })
set_hl("NonText",      { bg = "NONE" })
set_hl("LineNr",       { bg = "NONE" })
set_hl("LineNrAbove",  { bg = "NONE" })
set_hl("LineNrBelow",  { bg = "NONE" })
set_hl("SignColumn",   { bg = "NONE" })
set_hl("NormalFloat",  { bg = "NONE" })
set_hl("FloatBorder",  { bg = "NONE" })

-- Re-apply transparency if colorscheme is reloaded
vim.api.nvim_create_autocmd("ColorScheme", {
  group = vim.api.nvim_create_augroup("stylix_transparent", { clear = true }),
  pattern = "*",
  callback = function()
    set_hl("Normal",      { bg = "NONE" })
    set_hl("NonText",     { bg = "NONE" })
    set_hl("LineNr",      { bg = "NONE" })
    set_hl("LineNrAbove", { bg = "NONE" })
    set_hl("LineNrBelow", { bg = "NONE" })
    set_hl("SignColumn",  { bg = "NONE" })
    set_hl("NormalFloat", { bg = "NONE" })
    set_hl("FloatBorder", { bg = "NONE" })
  end,
})
