general {
    lock_cmd = pidof hyprlock || hyprlock                                     
    before_sleep_cmd = loginctl lock-session                                  # 休眠前锁定
}

listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r                 
}

listener { 
    timeout = 150                                          
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 
    on-resume = brightnessctl -rd rgb:kbd_backlight        
}

listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

listener {
    timeout = 330                                                                                  
    on-timeout = niri msg action power-off-monitors                                # Niri 关闭显示器命令
    on-resume = niri msg action power-on-monitors && brightnessctl -r              # Niri 开启显示器并恢复亮度
}

listener {
    timeout = 1800                                
    on-timeout = systemctl suspend                
}
