-- Matugen template for Neovim (outputs lua/generated/matugen.lua)
-- This template emits both `base_16` and `base_30`.
-- Syntax highlighting in lua/config/matugen.lua reads from these tables.
return {
  enabled = true,
  dark = {
    base_16 = {
      base00 = '{{colors.surface.dark.hex}}',
      base01 = '{{colors.surface_container_low.dark.hex}}',
      base02 = '{{colors.surface_container.dark.hex}}',
      base03 = '{{colors.outline_variant.dark.hex}}',
      base04 = '{{colors.on_surface_variant.dark.hex}}',
      base05 = '{{colors.on_surface.dark.hex}}',
      base06 = '{{colors.on_surface.dark.hex}}',
      base07 = '{{colors.on_surface.dark.hex}}',
      base08 = '{{colors.error.dark.hex}}',
      base09 = '{{colors.tertiary.dark.hex}}',
      base0A = '{{colors.secondary.dark.hex}}',
      base0B = '{{colors.primary.dark.hex}}',
      base0C = '{{colors.inverse_primary.dark.hex}}',
      base0D = '{{colors.primary_fixed.dark.hex}}',
      base0E = '{{colors.tertiary.dark.hex}}',
      base0F = '{{colors.error_container.dark.hex}}',
    },
    base_30 = {
      white = '{{colors.on_surface.dark.hex}}',
      darker_black = '{{colors.surface_dim.dark.hex}}',
      black = '{{colors.surface.dark.hex}}',
      black2 = '{{colors.surface_container_low.dark.hex}}',
      one_bg = '{{colors.surface_container.dark.hex}}',
      one_bg2 = '{{colors.surface_container_high.dark.hex}}',
      one_bg3 = '{{colors.surface_container_highest.dark.hex}}',
      grey = '{{colors.outline.dark.hex}}',
      grey_fg = '{{colors.outline_variant.dark.hex}}',
      grey_fg2 = '{{colors.on_surface_variant.dark.hex}}',
      light_grey = '{{colors.on_surface.dark.hex}}',
      red = '{{colors.error.dark.hex}}',
      baby_pink = '{{colors.error_container.dark.hex}}',
      pink = '{{colors.tertiary.dark.hex}}',
      line = '{{colors.outline_variant.dark.hex}}',
      green = '{{colors.primary.dark.hex}}',
      vibrant_green = '{{colors.primary_fixed.dark.hex}}',
      nord_blue = '{{colors.secondary.dark.hex}}',
      blue = '{{colors.primary.dark.hex}}',
      yellow = '{{colors.secondary_container.dark.hex}}',
      sun = '{{colors.tertiary_container.dark.hex}}',
      purple = '{{colors.tertiary.dark.hex}}',
      dark_purple = '{{colors.tertiary_container.dark.hex}}',
      teal = '{{colors.secondary.dark.hex}}',
      orange = '{{colors.error_container.dark.hex}}',
      cyan = '{{colors.inverse_primary.dark.hex}}',
      statusline_bg = '{{colors.surface_container_lowest.dark.hex}}',
      lightbg = '{{colors.surface_container_low.dark.hex}}',
      pmenu_bg = '{{colors.primary.dark.hex}}',
      folder_bg = '{{colors.primary.dark.hex}}',
    },
  },
  light = {
    base_16 = {
      base00 = '{{colors.surface.light.hex}}',
      base01 = '{{colors.surface_container_low.light.hex}}',
      base02 = '{{colors.surface_container.light.hex}}',
      base03 = '{{colors.outline_variant.light.hex}}',
      base04 = '{{colors.on_surface_variant.light.hex}}',
      base05 = '{{colors.on_surface.light.hex}}',
      base06 = '{{colors.on_surface.light.hex}}',
      base07 = '{{colors.on_surface.light.hex}}',
      base08 = '{{colors.error.light.hex}}',
      base09 = '{{colors.tertiary.light.hex}}',
      base0A = '{{colors.secondary.light.hex}}',
      base0B = '{{colors.primary.light.hex}}',
      base0C = '{{colors.inverse_primary.light.hex}}',
      base0D = '{{colors.primary.light.hex}}',
      base0E = '{{colors.tertiary.light.hex}}',
      base0F = '{{colors.error_container.light.hex}}',
    },
    base_30 = {
      white = '{{colors.on_surface.light.hex}}',
      darker_black = '{{colors.surface_dim.light.hex}}',
      black = '{{colors.surface.light.hex}}',
      black2 = '{{colors.surface_container_low.light.hex}}',
      one_bg = '{{colors.surface_container.light.hex}}',
      one_bg2 = '{{colors.surface_container_high.light.hex}}',
      one_bg3 = '{{colors.surface_container_highest.light.hex}}',
      grey = '{{colors.outline.light.hex}}',
      grey_fg = '{{colors.outline_variant.light.hex}}',
      grey_fg2 = '{{colors.on_surface_variant.light.hex}}',
      light_grey = '{{colors.on_surface.light.hex}}',
      red = '{{colors.error.light.hex}}',
      baby_pink = '{{colors.error_container.light.hex}}',
      pink = '{{colors.tertiary.light.hex}}',
      line = '{{colors.outline_variant.light.hex}}',
      green = '{{colors.primary.light.hex}}',
      vibrant_green = '{{colors.primary_fixed.light.hex}}',
      nord_blue = '{{colors.secondary.light.hex}}',
      blue = '{{colors.primary.light.hex}}',
      yellow = '{{colors.secondary_container.light.hex}}',
      sun = '{{colors.tertiary_container.light.hex}}',
      purple = '{{colors.tertiary.light.hex}}',
      dark_purple = '{{colors.tertiary_container.light.hex}}',
      teal = '{{colors.secondary.light.hex}}',
      orange = '{{colors.error_container.light.hex}}',
      cyan = '{{colors.inverse_primary.light.hex}}',
      statusline_bg = '{{colors.surface_container_lowest.light.hex}}',
      lightbg = '{{colors.surface_container_low.light.hex}}',
      pmenu_bg = '{{colors.primary.light.hex}}',
      folder_bg = '{{colors.primary.light.hex}}',
    },
  },
}
